name: Ruby

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: |
        bundle exec rake clobber spec build
        gem install --no-document "$(ls pkg/zopfli-*.gem)"
        cat <<EOF | ruby
        require "zopfli"
        require "zlib"
        if Zlib::Inflate.inflate(Zopfli.deflate(File.read("README.md"))) == File.read("README.md")
          puts "OK"
          exit 0
        else
          puts "NG"
          exit 0
        end
        EOF
