name: Publish Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run release task
      run: |
        mkdir -p ~/.gem
        cat << EOF > ~/.gem/credentials
        ---
        :github: Bearer ${{secrets.GITHUB_TOKEN}}
        :rubygems_api_key: ${{secrets.RUBYGEMS_API_KEY}}
        EOF
        chmod 600 ~/.gem/credentials
        bundle exec rake release[remote]
        rm -f ~/.gem/credentials
